CREATE TABLE Projects
(
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    TechStack NVARCHAR(500) NOT NULL,
    GitHubUrl NVARCHAR(500) NOT NULL,
    LiveUrl NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL
);